services:
  db:
    image: "postgres:17.2-alpine3.20"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  webserver:
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:8200:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata: