# Generated by Django 5.1.4 on 2024-12-23 22:51

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('Girokonto', 'Girokonto'), ('Tagesgeldkonto', 'Tagesgeldkonto'), ('Sparkonto', 'Sparkonto'), ('Depot', 'Depot')], max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='mtl. Budget')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.category')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date_start', models.DateField(verbose_name='Vertragsstart')),
                ('cancelation_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kündigungsfrist (in Monaten)')),
                ('minimum_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mindestlaufzeit (in Monaten)')),
                ('renewal_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Verlängerung (in Monaten)')),
                ('amount', models.FloatField(verbose_name='Betrag')),
                ('payment_date', models.DateField(null=True, verbose_name='regulärer Abbuchungstag')),
                ('payment_cycle', models.CharField(choices=[('m', 'monatlich'), ('q', 'quartalsweise'), ('h', 'halbjährlich'), ('y', 'jährlich')], max_length=4, verbose_name='Turnus')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Vertrag',
                'verbose_name_plural': 'Verträge',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Datum')),
                ('amount', models.FloatField(verbose_name='Betrag')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.category', verbose_name='Kategorie')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.contract', verbose_name='Vertrag')),
                ('counter_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.record')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ['-date', 'category'],
            },
        ),
    ]
