# Generated by Django 5.1.4 on 2025-03-08 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_category_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
