# Generated by Django 5.1.4 on 2025-05-27 09:19

from django.db import migrations, models


def add_tags(apps, schema_editor):
    Category = apps.get_model("finance", "Category")
    Record = apps.get_model("finance", "Record")

    def add_categories(record: Record, category: Category):
        """Traverse the hierarchy up"""
        record.tags.add(category)

        if category.parent:
            add_categories(record, category.parent)

    for record in Record.objects.all():
        if record.category:
            add_categories(record, record.category)


def remove_tags(apps, schema_editor):
    Record = apps.get_model("finance", "Record")

    for record in Record.objects.all():
        record.tags.clear()


class Migration(migrations.Migration):
    dependencies = [
        ('finance', '0004_alter_record_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='records', to='finance.category',
                                         verbose_name='Tags'),
        ),
        migrations.RunPython(add_tags, remove_tags)
    ]
