# Generated by Django 5.1.4 on 2025-03-07 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_remove_category_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('value_date', models.DateTimeField()),
                ('creditor', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(max_length=3)),
                ('transaction_type', models.TextField()),
                ('purpose', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_ignored', models.BooleanField(default=False)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.account')),
                ('is_counter_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
                ('records', models.ManyToManyField(related_name='transactions', to='finance.record')),
            ],
            options={
                'ordering': ('booking_date',),
            },
        ),
    ]
