# Generated by Django 5.1.4 on 2025-05-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('booking_date', 'creditor', 'purpose')},
        ),
    ]
